### PR TITLE
Created updater with support for custom locations

### PR DESCRIPTION
**Pull request by Iwuh**
Created an additional updater (updater-custom.bat) that has support for custom file locations.

### CODE REVIEW

**Comment by RhapsodySL** [comment]
Didn't know about setx, that's pretty neat!

I'll merge this if there's a way to remove the variable you're setting with setx, perhaps with another batch file. I'd rather not have this unusable if they enter the wrong file path or change their installation location.

**Comment by Iwuh** [comment]
Sure thing. Once I get home I'll write a script that removes the variable so that it can be set again.

**Comment by Iwuh** [comment]
Alright, there's now a script that will remove the custom location, letting the user set it again next time they run updater-custom.

**Comment by RhapsodySL** [comment]
Thanks! I'm going to go ahead and merge this, but I intend to move this into the main updater real fast.

**Comment by RhapsodySL** [comment]
So I tried using this on my Windows 10 computer, and apparently SETX isn't a valid command. Any idea what's up?

**Comment by RhapsodySL** [comment]
After testing this for a bit, I decided to revert it. As it turns out, it doesn't quite work. When you set the path at first, it requires administrator privileges. This is acceptable, although unideal. The thing is though, on the second run, when you try to run it without administrator privileges, it gives me an access denied error. When running it as administrator, it instead says that it can't find wget (presumably because it changed the operating directory). I can't fix this no matter what I try, and presumably, it's the fault of how this script is set up. Can you take a look at it?

**Comment by Iwuh** [comment]
Once I have time I'll see what I can do to fix it.

**Pull request merged**
